version: "3.1"
services:
  base-java-mongodb-service:
    container_name: base-java-mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: base-java-db
      MONGO_INITDB_ROOT_USERNAME: base-java-usr
      MONGO_INITDB_ROOT_PASSWORD: base-java-psw
    ports:
      - 27017:27017
    volumes:
      - ./database/mongodb/scripts/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - ./database/mongodb/data/:/data/db
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: base-java-usr
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: base-java-psw
  base-java-springboot-service:
    container_name: base-java-springboot
    image: jdk:8
    build:
      context: ./docker/
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
    entrypoint: ["/bin/sh", "./docker/entrypoint.sh"]
    # command: mvn exec:java -Dexec.mainClass=br.com.ruyjfs.base -Plocal
    command: ./mvnw spring-boot:run
    tty: true
    restart: on-failure
    links:
      # - redis:redis
      - base-java-mongodb-service:base-java-mongodb-service
    depends_on:
      # - redis
      - base-java-mongodb-service
    # redis:
    #   container_name: ${APP_NAME}-redis
    #   image: redis:alpine
    #   ports:
    #   - 6379:6379
    #   tty: true
    #   restart: on-failure
    # db:
    #   container_name: ${APP_NAME}-db
    #   image: postgres:alpine
    #   environment:
    #     POSTGRES_DB: ${APP_NAME}
    #     POSTGRES_USER: ${APP_NAME}
    #     POSTGRES_PASSWORD: ${APP_NAME}
    #   ports:
    #   - 5432:5432
    #   tty: true
    #   restart: on-failure
    # links:
    # - redis:redis
    # - db:db
    # depends_on:
    #   - redis
    #   - db
  # front:
  #   container_name: ${APP_NAME}-front
  #   image: ${APP_NAME}-front:latest
  #   build:
  #     context: ./front/docker/
  #   volumes:
  #   - ./front/:/var/wwwn
  #   ports:
  #   - 4200:4200
  #   entrypoint: [ "/bin/sh" , "./docker/entrypoint.sh" ]
  #   command: ng serve --host 0.0.0.0
  #   links:
  #     - back:back
  #   depends_on:
  #     - back
  #   tty: true
  #   restart: on-failure
